# docker-compose.yml
services:
  web:
    image: "ghcr.io/remla23-team18/model-service:latest"
    ports:
      - 8080:8080
  app:
    depends_on:
      - web
    image: "ghcr.io/remla23-team18/app:latest"
    ports:
      - 3000:3000
