{
 "title": "Restaurant Review Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Model Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Predictions with <= N words",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Predictions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(le) (text_length_bucket)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Accuracy Over Time",
   "type": "timeseries",
   "description": "Accuracy is based on feedback provided by user",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(version) (total_accuracy)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Predictions Per Minute",
   "type": "timeseries",
   "description": "Number of predictions made per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(version) (rate(predict_calls_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feedback given per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by(version) (rate(total_predictions_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}