# remla.yml
apiVersion: v1
kind: Service
metadata:
  name: web-serv
  labels:
    app: metrics-web
spec:
  selector:
    app: web
  ports:
    - port: {{.Values.web.port}}
      targetPort: {{.Values.web.targetPort}}
---
apiVersion: v1
kind: Service
metadata:
  name: app-serv
  labels:
    app: metrics-app
spec:
  selector:
    app: app
  ports:
    - port: {{.Values.app.port}}
      targetPort: {{.Values.app.targetPort}}